// Secrets set via `wrangler secret put` — not generated by `wrangler types`
interface Env {
  GITHUB_CLIENT_ID: string;
  GITHUB_CLIENT_SECRET: string;
  WORKER_URL: string;
  OAUTH_KV: KVNamespace;
  MCP_AGENT: DurableObjectNamespace;
}
